docker run --rm -p 7860:7860 mn9206986/workspace bash -c "
apt-get update && apt-get install -y curl &&
curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared &&
chmod +x /usr/local/bin/cloudflared &&

# chạy app nền (KHÔNG start.sh)
<COMMAND_START_APP> &

cloudflared tunnel --url http://localhost:7860
"
